### ISSUE TITLE
> @mchmielarski

### ISSUE THREAD

**Issue by rez20004** [opentrace-community/opentrace-cloud-functions#9]
> @mchmielarski
> I called await storeUploadCodes(['1234']); inside getUploadToken.ts class in the getUploadToken to set the PIN and it seems to work fine. I was able to upload data from the App using the PIN 1234

hi sorry, it tried this but does not seems to work. can someone provide some explanation of  where and how to put this in the getUploadToken

_Originally posted by @rez20004 in https://github.com/opentrace-community/opentrace-cloud-functions/issues/6#issuecomment-613275092_

**Comment by simonry14** [comment]
Yes. I would also want to know this. Thanks in advance

**Comment by bunhann** [comment]
The function storeUploadCodes is not call. It doesn't create document in firestore. So, when the application call retrieveUploadCodes, it provide an error in this app.
I also want to know where to implement this storeUploadCodes.

**Comment by rez20004** [comment]
I have also observed that access to the getupload token is forbidden when i checked the trigger http section in the cloud functions. Thats could be a reason why it is not working. I have to look at all the access controls they are the same for the other functions. 
When i tried to open cloud firestore it says this project is set up to use Cloud Firestore in Datastore mode. This mode can only be accessed from Google Cloud Platform. 
can someone help on this please

**Comment by bunhann** [comment]
Hi, @rez20004 . 
You can go to Google Cloud Platform -> Data Store then Enable the Cloud Firestore in Native mode.

**Comment by rez20004** [comment]
> Hi, @rez20004 .
> You can go to Google Cloud Platform -> Data Store then Enable the Cloud Firestore in Native mode.

HI bunhann,

I tried but I can't go to firestore in native mode. It is redirecting me to google cloud datastore mode. I don't know whether this is causing the problem where the codes document is not being created!!

**Comment by qtangs** [comment]
@bunhann is right, Cloud Firestore in Native mode needs to be enabled at https://console.cloud.google.com/firestore/data

Do take note of below warning, documented at 
https://cloud.google.com/datastore/docs/firestore-or-datastore: 

> Warning: Once you select Firestore in Datastore mode and execute the first write on the database, you cannot switch to Firestore in Native mode.

Regarding the upload code logic, `retrieveUploadCodes` can be modified to return a fixed code for testing purpose.
For production, encrypts the code and stores it in the Cloud Firestore.
Storage is done by `storeUploadCodes`, for which we did not include a trigger, as there can be different policies to apply it: You can either call this function from a Javascript/Typescript script and manually execute it or create a scheduled Firebase function (https://firebase.google.com/docs/functions/pubsub-events) to generate and store the upload codes on a periodic basis.

**Comment by rburhum** [comment]
> Hi, @rez20004 .
> You can go to Google Cloud Platform -> Data Store then Enable the Cloud Firestore in Native mode.

You can only do this if you have not made any edits... if you tried to mock with this to make the app work, you are screwed. Basically you can delete everything, but the system won't let you enable Native mode. You will have to start a new project. 

Extremely painful lesson this week. :(

**Comment by nosecc** [comment]
@rburhum i figure it out sometime back and i have already tried with new projects and got the native mode up and running. But the temporary solution given (using storeUploadCodes)  where it create a doc with codes inside still not working .

**Comment by siilats** [comment]
if anyone wants to test a live version, we have the estonian version up in testflight and it will accept a mobile phone number from any country https://testflight.apple.com/join/oEmt78kM

**Comment by siilats** [comment]
> @rburhum i figure it out sometime back and i have already tried with new projects and got the native mode up and running. But the temporary solution given (using storeUploadCodes) where it create a doc with codes inside still not working .

you need to click on it twice because storeUploadCodes uses a future so first time the code will not be there

**Comment by esQmo** [comment]
Would you include an Android version also?  @siilats

**Comment by rez20004** [comment]
I figure it and therefore closing this issue. Thanks all.

**Comment by valduze** [comment]
Hi @qtangs,
I am running Firebase in Native Mode, I still cannot get the upload pin.
You said
`Regarding the upload code logic, retrieveUploadCodes can be modified to return a fixed code for testing purpose`

How do I do that, let's for example, I want to upload code 1234
Thanks,
Jongi

**Comment by alexissinglaire** [comment]
@valduze 
Hi, you can insert the code await storeUploadCodes(['1234']) after The console.log inside getUploadToken.ts class as following; 

const getUploadToken = async (...
  console.log('getUploadToken:', 'uid', uid, 'data', data, 'ip', context.rawRequest.ip);
   await storeUploadCodes(['1234'])
   let valid = false;
    if (data) {

**Comment by valduze** [comment]
@alexissinglaire 
Thanks I tried that but it doesn't work, it still says invalid pin
getUploadToken: uid 9IzyJH6YhoX5OqZFbALrXAO3xRy2 data 123456 ip 111.1111.111.111

I redeployed the functions and also reinstalled my Android app, no luck.
Thanks,
Jongi

**Comment by alexissinglaire** [comment]
@valduze: can you display the slice of code (few lines) in getUploadToken.ts that you have changed?

Is there any error shown in log in firebase functions console?

**Comment by valduze** [comment]
Hi @alexissinglaire,
Here is the code:


```
const getUploadToken = async (uid: string, data: any, context: functions.https.CallableContext) => {
  console.log('getUploadToken:', 'uid', uid, 'data', data, 'ip', context.rawRequest.ip);

  await storeUploadCodes(['123456']);
  let valid = false; 

```

It shows my call for upload on Firebase logs:


`3:42:39.021 am |  getUploadToken: uid 9IvyJH6YhoX5OqZFbALrXAO3xRy1 data 123456 ip 111.111.111.111
`
But on the upload window in my Android app it says "invalid PIN".
Thanks,
Jongi

**Comment by alexissinglaire** [comment]
@valduze :

can you give us screenshot the firebase log starting from the line that you gave us until the message 'data is not valid code'.

refer to my logs below for good case:
![image](https://user-images.githubusercontent.com/17283778/81461356-ae856880-91dd-11ea-821b-cc790311324e.png)

is there any error shown in the android studio logcat when you trigger the 'upload data' button after keyed in your PIN ?

another things is, did you put extra space when you enter the PIN in android app?

**Comment by valduze** [comment]
@alexissinglaire 
Please find attached
<img width="1153" alt="Screenshot 2020-05-09 at 04 31 32" src="https://user-images.githubusercontent.com/3236023/81461725-0c01c100-91ae-11ea-8011-05bf94fe4925.png">
and code
<img width="944" alt="Screenshot 2020-05-09 at 04 32 48" src="https://user-images.githubusercontent.com/3236023/81461743-2cca1680-91ae-11ea-800d-04c74c890dcf.png">
Thanks

**Comment by valduze** [comment]
and
<img width="1123" alt="Screenshot 2020-05-09 at 04 37 54" src="https://user-images.githubusercontent.com/3236023/81461868-e5905580-91ae-11ea-891d-6e75dfbe1353.png">

**Comment by alexissinglaire** [comment]
@valduze : from the firebase function logs it shows that something wrong with your permission setup for secret manager secret accessor role. which user in IAM that you granted the permission for the role 'secret manager secret accessor'?

**Comment by valduze** [comment]
I am getting an error getting temporal IDs in logcat: D/TempIDManager:  NOT-IDLE [TempID] Error getting Temporary IDs

**Comment by alexissinglaire** [comment]
@valduze : hi, you can analyze the firebase functions log for any error in the cloud functions. the error shown in the logcat referring to cloud functions 'getTempIDs.ts' , check for any error produce by this function. 

you can also check whether you have define the secret value correctly based on the document given.

another thing for config.ts in the /functions/src folder, the value i currently use is 'aes-256-gcm' for parameter defaultAlgorithm.

**Comment by valduze** [comment]
Hi,
I fixed my tempids, the issue was with wring name on secret. Now it writes upload to get database, now where do I get upload PIN?
Thanks so much for your help.
Regards,
Jongi

**Comment by alexissinglaire** [comment]
@valduze: the upload pin is hardcoded using this code
await storeUploadCodes(['123456']);

If you want to implement solution without hardcoded the pin, you need to implement your own solution . In this repo the author did not provide solution for this portion.

**Comment by antu12** [comment]
@valduze 
So in my case I created a new function with some changes to storeUploadCodes so that I can create a web portal for admins to upload a code. 

So after the code is in the firestore the user can press upload and upload his data as a positive patient right?

But it seems I'm still getting an invalid code error after a long time of loading, maybe app's having trouble to upload.

You have any updates ? It would help a lot to understand the full user journey.
Thanks.

<img width="1145" alt="Screenshot 2020-05-28 at 4 37 04 AM" src="https://user-images.githubusercontent.com/10395647/83079529-db6ec200-a09d-11ea-835f-5ada6340640d.png">
